version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./image_colorizer/media:/app/media
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1